# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_type', models.CharField(choices=[('adm', 'ADMINS'), ('mod', 'MODERATORS'), ('aut', 'AUTHORS'), ('sub', 'SUBSCRIBERS'), ('all', 'ALL')], max_length=3, verbose_name='Mailing type')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Mail',
                'verbose_name_plural': 'Mails',
            },
        ),
    ]
