# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('cyc272', 'Cycles 2.72'), ('int272', 'Internal 2.72')], max_length=6, verbose_name='Engine version')),
                ('type', models.CharField(choices=[('s', 'Solid'), ('c', 'Cloth'), ('u', 'UV unwrapped'), ('f', '(Not Implemented) Fluid'), ('v', '(Not Implemented) Volume'), ('e', 'Emission')], max_length=1, verbose_name='Scene type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(blank=True, upload_to='uploads/scenes/', verbose_name='Scene file')),
                ('image', models.ImageField(blank=True, upload_to='uploads/scenes/', verbose_name='Original image')),
                ('thumb_big', models.ImageField(blank=True, upload_to='uploads/scenes/', verbose_name='Thumbnail (big)')),
                ('thumb_small', models.ImageField(blank=True, upload_to='uploads/scenes/', verbose_name='Thumbnail (small)')),
            ],
            options={
                'ordering': ['engine'],
                'verbose_name': 'Scene',
                'verbose_name_plural': 'Scenes',
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_file', models.FileField(upload_to=uploads.models.get_upload_filename, verbose_name='Uploaded file')),
                ('name_in_file', models.CharField(max_length=50, verbose_name='Material name in file')),
                ('engine', models.CharField(choices=[('cyc272', 'Cycles 2.72'), ('int272', 'Internal 2.72')], max_length=6, verbose_name='Engine version')),
                ('scene', models.CharField(choices=[('s', 'Solid'), ('c', 'Cloth'), ('u', 'UV unwrapped'), ('f', '(Not Implemented) Fluid'), ('v', '(Not Implemented) Volume'), ('e', 'Emission')], max_length=1, verbose_name='Scene type')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload date')),
                ('status', models.CharField(choices=[('w', 'Pending'), ('r', 'Rendering'), ('a', 'Approving'), ('p', 'Publishing'), ('d', 'Deleting'), ('e', 'Error')], default='w', max_length=1, verbose_name='Status')),
                ('render_started', models.DateTimeField(blank=True, null=True, verbose_name='Render started at')),
                ('render_finished', models.DateTimeField(blank=True, null=True, verbose_name='Render finished at')),
                ('error', models.TextField(blank=True, verbose_name='Error description')),
                ('storage', models.FileField(blank=True, upload_to=uploads.models.get_rendered_filename, verbose_name='Storage')),
                ('image', models.ImageField(blank=True, upload_to=uploads.models.get_rendered_filename, verbose_name='Rendered image')),
                ('user_approved', models.BooleanField(default=False, verbose_name='Approved by user')),
                ('admin_approved', models.BooleanField(default=False, verbose_name='Approved by admin')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='materials.Category')),
            ],
            options={
                'ordering': ['date'],
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
            },
        ),
    ]
